spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        metadata_builder_contributor: com.example.backend.jpa.SqlFunctionsMetadataBuilderContributor
  datasource:
    url: ${database_url}
    username: ${database_username}
    password: ${database_password}